# Generated by Django 3.2.25 on 2025-02-17 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_image_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='days_limit',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='end_date',
        ),
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='image',
            name='date_limit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='date_limit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
