# Generated by Django 3.2.25 on 2025-02-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20250217_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='image',
            name='date_limit',
        ),
        migrations.RemoveField(
            model_name='image',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='image',
            name='done',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
