# Generated by Django 3.2.25 on 2025-02-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20250220_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='date_limit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
