# Generated by Django 3.2.25 on 2025-02-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_subject_date_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='date_limit',
        ),
        migrations.AddField(
            model_name='subject',
            name='date_limit_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='date_limit_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='date_limit_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
