# Generated by Django 3.2.25 on 2025-02-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20250225_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='date_limit_month',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='date_limit_year',
        ),
    ]
