# Generated by Django 3.2.25 on 2025-02-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_subject_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='date_limit_day',
        ),
        migrations.AddField(
            model_name='subject',
            name='date_limit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
